### ISSUE TITLE
I can't download

### ISSUE THREAD

**Issue by TheNickname99** [EmanuelG-Gaming/erekir-expansion#2]
(Sorry for bad english)

I can't download any version of mod. This problem also shows when i download it from file.

![Screenshot_20220629-080553_Mindustry BE](https://user-images.githubusercontent.com/107668259/176356230-3eb54b68-8a00-429b-9108-442b38ba4136.jpg)

**Comment by EmanuelG-Gaming** [comment]
Have you also downloaded the mod from actions?
Sorry if I responded late.

**Comment by TheNickname99** [comment]
Oh, thanks, it's download now from actions.

**Comment by EmanuelG-Gaming** [comment]
np

**Comment by MrRoomba** [comment]
What about mobile devices
I

**Comment by EmanuelG-Gaming** [comment]
> What about mobile devices I

If you look into actions, it both features a download compatible for android and windows.

Yes, I'm a mobile modder.
